<!-- start: DYNAMIC TABLE -->
<div class="container-fluid container-fullw bg-white">
    <div class="row">
        <div class="col-md-12">
            <h5 class="over-title margin-bottom-15"><span class="text-bold">@manage_label@@orders_label@</span></h5>
            <div class="row">
                <div class="col-sm-4">
                    <div class="input-group"><span class="input-group-addon"><i class="fa fa-search"></i></span><input
                            type="text" placeholder="@search_input_ph@" id="search-table" value="iC{{SEARCH_Q}}"
                            class="form-control"></div>
                </div>
                <div class="col-sm-5">
                </div>
                <div class="col-sm-3  pull-left">
                </div>
            </div>
            <input type="hidden" id="orders_total" value="0">
            <input type="hidden" id="first_get" value="0">
            <div class="table-responsive">
                <table class="table-striped" id="ordtbl">
                    <thead>
                    <tr>
                        <th>@count_label@</th>
                        <th>@req_order_number_label@</th>
                        <th>@req_order_cost_label@</th>
                        <th>@pos_dsc_label@</th>
                        <th>@req_order_delv_cost_label@</th>
                        <th>@req_order_detailes_label@</th>
                        <th>@assigned_delv_label@</th>
                        <th>@assigned_wrk_label@</th>
                        <th>@added_time_label@</th>
                        <th>@city_label@</th>
                        <th>@state_label@</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>