<!-- start: DYNAMIC TABLE -->
<div class="container-fluid container-fullw bg-white">
    <div class="row">
        <div class="col-md-12">
            <h5 class="over-title margin-bottom-15"><span class="text-bold">@clients_label@</span>
            </h5>
            <div class="row">
                <div class="col-sm-3">
                    <div class="input-group"><span class="input-group-addon"><i class="fa fa-search"></i></span><input
                                type="text" placeholder="@search_input_ph@" id="search-table" class="form-control">
                    </div>
                </div>
                <div class="col-sm-9">

                </div>
            </div>
            <div class="table-responsive">
                <table class="table-striped" id="datatbl">
                    <thead>
                    <tr>
                        <th>@count_label@</th>
                        <th>@name_label@</th>
                        <th>@city_label@</th>
                        <th>@state_label@</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
