<!-- START CONTAINER FLUID -->
iC{{USER_MODAL}}
<div class="container-fluid container-fullw">
    <div class="row">
        <div class="col-md-12">
            <h5 class="over-title margin-bottom-15"><span class="text-bold">@manage_label@iC{{VIEW_TITLE}}</span></h5>
            <form enctype="multipart/form-data" class="add-form" id="inputForm">
                iC{{VIEW_CONTENT}}
            </form>
        </div>
    </div>
</div>