<legend><b>@client_info_label@</b></legend>
<div class="row">
    <div class="col-xs-12">
        @req_client_name_label@ : <b>iC{{ORDER_USER_NAME}}</b>
    </div>
    <div class="col-xs-12">
        @req_client_phone_label@ : <b>iC{{ORDER_USER_PHONE}}</b>
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
        @city_label@ : <b>iC{{ORDER_USER_AREA}}</b><br>
        @req_client_address_label@ : <b>iC{{ORDER_USER_ADDRESS}}</b>
    </div>
</div>