<!-- Modal -->
<div class="modal fade slide-up" id="edit-order" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
     aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog modal-dialog modal-sm">
        <div class="modal-content bg-white">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">@edit_btn@</h4>
            </div>

            <div id="editcontent">

            </div>

        </div>
    </div>
</div>