<!-- Modal -->
<div class="modal fade slide-up" id="changewrkmodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
     aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog modal-dialog modal-sm">
        <div class="modal-content bg-white">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">@change_wrk_label@</h4>
            </div>
            <form enctype="multipart/form-data" method="post" action="javascript:void(0)" class="add-form"
                  id="changewrkform">
                <div class="modal-body">
                    <input type="hidden" id="eordid" name="item_id"/>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label for="wrkcsel">
                                    @change_wrk_label@
                                </label>
                                <select id="wrkcsel" name="order_worker_id" class="form-control" required>

                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-warning btn-o" data-dismiss="modal">
                        @cancel_btn@
                    </button>
                    <button id="changewrkbtn" type="button" class="btn btn-success">
                        @change_wrk_label@
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>