<div class="checkbox clip-check check-success checkbox-inline"><input type="checkbox" name="type[]" id="connectchk"
                                                                      value="1" checked=""><label for="connectchk">@connect_delv_order@</label>
</div>
<div class="checkbox clip-check check-success checkbox-inline"><input type="checkbox" name="type[]" id="storechk"
                                                                      value="1"><label
            for="storechk">@self_delv_order@</label></div>
