<!-- Modal -->
<div class="modal fade slide-up" id="refusemodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
     aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog modal-dialog modal-sm">
        <div class="modal-content bg-white">
            <form enctype="multipart/form-data" method="post" action="javascript:void(0)" class="add-form"
                  id="refuseform">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel">@ord_refuse_btn@</h4>
                    <div class="checkbox clip-check check-success checkbox-inline"><input
                                type="checkbox" id="suspenduser" name="suspend" value="1"><label
                                for="suspenduser">@suspend_btn@ @user_label@</label></div>
                </div>
                <div class="modal-body">
                    <input type="hidden" id="rordid" name="item_id"/>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label class="control-label">
                                    @refuse_reason@ <span class="symbol required"></span></label>
                                <input type="text" class="form-control" name="reason" required>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-success btn-o" data-dismiss="modal">
                        @cancel_btn@
                    </button>
                    <button id="rOrderBtn" type="button" class="btn btn-danger">
                        @ord_refuse_btn@
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>