<div class="modal-body">
    <div class="row">
        <div class="col-sm-4">
            iC{{ITEM_MAIN_IMG}}
            @item_code_label@ : iC{{ITEM_CODE}}<br>
            iC{{ITEM_PRICE}}<br>
            iC{{CAT_INFO}}
            iC{{ITEM_INVENTORY}}
            @state_label@ : iC{{ITEM_ACTIVE}}
        </div>
        <div class="col-sm-8">
            @title_in_lang@@ar_lang@ : iC{{ITEM_TITLE_AR}}
            <hr>
            @des_in_lang@@ar_lang@ : iC{{ITEM_DESC_AR}}
            <hr>
            @title_in_lang@@en_lang@ : iC{{ITEM_TITLE_EN}}
            <hr>
            @des_in_lang@@en_lang@ : iC{{ITEM_DESC_EN}}
            <hr>
        </div>
    </div>
</div>