<!-- === Our Services =========== -->
<div class="flat-section">
    <div class="section-title">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <h2>iC{{PAGE_TITLE}}</h2>
                </div><!-- .col-md-8 end -->
            </div><!-- .row end -->
        </div><!-- .container end -->
    </div><!-- .section-title end -->

    <div class="section-content">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    iC{{MORE_CONTENT}}
                </div>
            </div><!-- .col-md-12 end -->
        </div><!-- .row end -->
    </div><!-- .container end -->

</div>
<!-- .section-content end -->