<!-- start: FOURTH SECTION -->
<div class="container-fluid container-fullw bg-white">
    <div class="row">
        <div class="col-xs-12 col-sm-5">
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-white no-radius">
                        <div class="panel-body padding-20 text-center">
                            <div class="space10">
                                <h4 class="text-dark no-margin">@app_online_label@</h4>
                                <span class="badge badge-success margin-top-10"><div id="apponline">0</div></span>
                            </div>
                            <div class="sparkline-4 space10">
                                <span></span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="panel panel-white no-radius">
                        <div class="panel-body padding-20 text-center">
                            <div class="space10">
                                <h4 class="text-dark no-margin">@web_online_label@</h4>
                                <span class="badge badge-danger margin-top-10"><div id="webonline">0</div></span>
                            </div>
                            <div class="sparkline-5 space10">
                                <span></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-sm-7">
            <div class="panel panel-white" id="userstate">
                <div class="panel-heading">
                    <h4 class="panel-title text-primary">@users_state@</h4>
                    <div class="panel-tools">
                        <a data-original-title="Refresh" data-toggle="tooltip" data-placement="top"
                           class="btn btn-transparent btn-sm" id="reloadurep" href="javascript:void(0)"><i
                                    class="ti-reload"></i></a>
                    </div>
                </div>
                <div class="panel-body">
                    <ul class="timeline-xs margin-top-15 margin-bottom-15">
                        <li class="timeline-item danger">
                            <div class="margin-right-15">
                                <p>
                                    @total_users_label@ : <span class="badge badge-danger margin-top-10">(<span
                                                id="tregu">0</span>)</span>
                                </p>
                            </div>
                        </li>
                        <li class="timeline-item">
                            <div class="margin-right-15">
                                <p>
                                    @total_reg_face_app@ : <span class="badge badge-default margin-top-10">(<span
                                                id="trufapp">0</span>)</span>
                                </p>
                            </div>
                        </li>
                        <li class="timeline-item">
                            <div class="margin-right-15">
                                <p>
                                    @total_reg_form_app@ : <span class="badge badge-success margin-top-10">(<span
                                                id="trufrmapp">0</span>)</span>
                                </p>
                            </div>
                        </li>
                        <li class="timeline-item">
                            <div class="margin-right-15">
                                <p>
                                    @total_reg_form_web@ : <span class="badge badge-inverse margin-top-10">(<span
                                                id="trufrmweb">0</span>)</span>
                                </p>
                            </div>
                        </li>
                        <li class="timeline-item">
                            <div class="margin-right-15">
                                <p>
                                    @total_reg_face_web@ : <span class="badge badge-default margin-top-10">(<span
                                                id="trufweb">0</span>)</span>
                                </p>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end: FOURTH SECTION -->