<!-- === Our Services =========== -->
<div class="flat-section">
    <div class="section-content">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                    <h2>404 @error_label@</h2>
                </div>
            </div><!-- .col-md-12 end -->
        </div><!-- .row end -->
    </div><!-- .container end -->
</div>
<!-- .section-content end -->