<!-- Modal -->
<div class="modal fade slide-up" id="viewitem" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog modal-lg">
        <div class="modal-content bg-white">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">@view_info_btn@
                    <div class="checkbox clip-check check-success checkbox-inline"><input type="checkbox"
                                                                                          id="payablechk" value="1"
                                                                                          checked><label
                                for="payablechk">@payable_amount_label@</label></div>
                    <div class="checkbox clip-check check-success checkbox-inline"><input type="checkbox"
                                                                                          id="detailschk" value="1"
                                                                                          checked><label
                                for="detailschk">@orders_details_label@</label></div>
                    <div class="checkbox clip-check check-success checkbox-inline"><input type="checkbox" id="totalchk"
                                                                                          value="1" checked><label
                                for="totalchk">@total_label@</label></div>
                    <a class="btn btn-sm btn-info" href="javascript:void(0);"
                       onclick="$('#viewcontent').printThis();"><i class="fa fa-print"></i> @print_button@</a>
                </h4>
            </div>

            <div id="viewcontent">
            </div>

        </div>
    </div>
</div>