<!-- === Our Services =========== -->
<div class="flat-section">
    <div class="section-title">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <h2>@reset_password_label@</h2>
                </div><!-- .col-md-8 end -->
            </div><!-- .row end -->
        </div><!-- .container end -->
    </div><!-- .section-title end -->

    <div class="section-content">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <form id="form-reset-pass" class="form inputs-underline" action="javascript:void(0)">
                        <input type="hidden" name="resetToken" value="iC{{RESET_TOKEN}}">
                        <div class="form-group">
                            <label for="password">@new_password_label@</label>
                            <input type="password" class="form-control" name="password" id="password"
                                   placeholder="@password_ph@" required>
                        </div>
                        <!--end form-group-->
                        <div class="form-group">
                            <label for="confirm_password">@conf_password_label@</label>
                            <input type="password" class="form-control" name="confirm_password" id="confirm_password"
                                   placeholder="@conf_password_ph@" required>
                        </div>
                        <!--end form-group-->
                        <div class="btn btn-primary hidden" id="error"></div>
                        <div class="form-group center">
                            <button type="submit" id="submit-btn" class="btn btn-primary width-100">
                                @reset_password_label@
                            </button>
                        </div>
                    </form>
                </div>
            </div><!-- .col-md-12 end -->
        </div><!-- .row end -->
    </div><!-- .container end -->

</div>
<!-- .section-content end -->