<div class="sidebar app-aside" id="sidebar">
    <div class="sidebar-container perfect-scrollbar">
        <nav>
            <!-- start: SEARCH FORM -->
            <div class="search-form">
                <a class="s-open" href="javascript:void(0)">
                    <i class="ti-search"></i>
                </a>
                <form class="navbar-form" role="search" action="iC{{LOCATION_URL}}">
                    <a class="s-remove" href="javascript:void(0)" target=".navbar-form">
                        <i class="ti-close"></i>
                    </a>
                    <div class="form-group">
                        <input type="text" class="form-control" name="search_q" placeholder="@search_loc_ph@">
                        <button class="btn search-button" type="submit">
                            <i class="ti-search"></i>
                        </button>
                    </div>
                </form>
            </div>
            <!-- end: SEARCH FORM -->
            <!-- start: MAIN NAVIGATION MENU -->
            <div class="navbar-title">
                <span>@main_nav_label@</span>
            </div>
            <ul class="main-navigation-menu">
                <li id="home_sp" class="">
                    <a href="iC{{HOME_URL}}">
                        <div class="item-content">
                            <div class="item-media">
                                <i class="ti-home"></i>
                            </div>
                            <div class="item-inner">
                                <span class="title"> @dashboard_label@ </span>
                            </div>
                        </div>
                    </a>
                </li>
                <li id="cats_sp">
                    <a href="iC{{CATEGORIES_URL}}">
                        <div class="item-content">
                            <div class="item-media">
                                <i class="ti-layers-alt"></i>
                            </div>
                            <div class="item-inner">
                                <span class="title"> @cats_label@ </span>
                            </div>
                        </div>
                    </a>
                </li>
                <li id="loc_sp">
                    <a href="iC{{LOCATION_URL}}">
                        <div class="item-content">
                            <div class="item-media">
                                <i class="ti-location-pin"></i>
                            </div>
                            <div class="item-inner">
                                <span class="title"> @directory_label@ </span>
                            </div>
                        </div>
                    </a>
                </li>
                <li id="ads_sp">
                    <a href="iC{{ADS_URL}}">
                        <div class="item-content">
                            <div class="item-media">
                                <i class="fa  fa-dot-circle-o"></i>
                            </div>
                            <div class="item-inner">
                                <span class="title"> @ads_label@ </span>
                            </div>
                        </div>
                    </a>
                </li>
                <li id="users_sp">
                    <a href="iC{{USERS_URL}}">
                        <div class="item-content">
                            <div class="item-media">
                                <i class="fa fa-user"></i>
                            </div>
                            <div class="item-inner">
                                <span class="title"> @users_label@ </span>
                            </div>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- end: MAIN NAVIGATION MENU -->
            <!-- start: CORE FEATURES -->
            <div class="navbar-title">
                <span>@mob_app_nav_label@</span>
            </div>
            <!-- start:
            <ul class="folders">
                <li>
                    <a href="pages_calendar.html">
                        <div class="item-content">
                            <div class="item-media">
                                <span class="fa-stack"> <i class="fa fa-square fa-stack-2x"></i> <i class="fa fa-terminal fa-stack-1x fa-inverse"></i> </span>
                            </div>
                            <div class="item-inner">
                                <span class="title"> Calendar </span>
                            </div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="pages_messages.html">
                        <div class="item-content">
                            <div class="item-media">
                                <span class="fa-stack"> <i class="fa fa-square fa-stack-2x"></i> <i class="fa fa-folder-open-o fa-stack-1x fa-inverse"></i> </span>
                            </div>
                            <div class="item-inner">
                                <span class="title"> Messages </span>
                            </div>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- end: CORE FEATURES -->
            <!-- start: DOCUMENTATION BUTTON -->
            <div class="wrapper">
                <a href="https://www.3lfraza.com" target="_blank" class="button-o">
                    <i class="ti-help"></i>
                    <span>3lfraza</span>
                </a>
            </div>
            <!-- end: DOCUMENTATION BUTTON -->
        </nav>
    </div>
</div>
			