<!-- start: MAIN NAVIGATION MENU -->
<div class="navbar-title">
    <span>@main_nav_label@</span>
</div>
<ul class="main-navigation-menu">
    <li id="home_sp" class="">
        <a href="iC{{HOME_URL}}">
            <div class="item-content">
                <div class="item-media">
                    <i class="ti-home"></i>
                </div>
                <div class="item-inner">
                    <span class="title"> @dashboard_label@ </span>
                </div>
            </div>
        </a>
    </li>