<script src="iC{{CONFIG_THEME_URL}}/backend/vendor/jquery/jquery.min.js"></script>
<script src="iC{{CONFIG_THEME_URL}}/backend/vendor/bootstrap/js/bootstrap.min.js"></script>
<script src="iC{{CONFIG_THEME_URL}}/backend/vendor/modernizr/modernizr.js"></script>
<script src="iC{{CONFIG_THEME_URL}}/backend/vendor/jquery-cookie/jquery.cookie.js"></script>
<script src="iC{{CONFIG_THEME_URL}}/backend/vendor/perfect-scrollbar/perfect-scrollbar.min.js"></script>
<script src="iC{{CONFIG_THEME_URL}}/backend/vendor/switchery/switchery.min.js"></script>
<script src="iC{{CONFIG_THEME_URL}}/sound/jquery.playSound.js"></script>