<div class="row">
    <div class="col-sm-12">
        <div class="form-group">
            <label class="control-label">
                <i class="fa fa-user"></i> @users_label@
            </label>
            <div class="checkbox clip-check check-inverse checkbox-inline"><input type="checkbox" id="usersview"
                                                                                  name="perm[users][view]"
                                                                                  value="1"><label for="usersview">@view_label@</label>
            </div>
            <div class="checkbox clip-check check-info checkbox-inline"><input type="checkbox" id="usersadd"
                                                                               name="perm[users][add]" value="1"><label
                        for="usersadd">@add_label@</label></div>
            <div class="checkbox clip-check check-danger checkbox-inline"><input type="checkbox" id="usersdel"
                                                                                 name="perm[users][del]"
                                                                                 value="1"><label for="usersdel">@delete_btn@</label>
            </div>
            <div class="checkbox clip-check check-warning checkbox-inline"><input type="checkbox" id="usersedit"
                                                                                  name="perm[users][edit]"
                                                                                  value="1"><label for="usersedit">@edit_btn@</label>
            </div>
            <div class="checkbox clip-check check-success checkbox-inline"><input type="checkbox" id="usersactv"
                                                                                  name="perm[users][actv]"
                                                                                  value="1"><label for="usersactv">@activiate_btn@</label>
            </div>
            <hr>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <div class="form-group">
            <label class="control-label">
                <i class="fa fa-lock"></i> @privacy_label@
            </label>
            <div class="checkbox clip-check check-inverse checkbox-inline"><input type="checkbox" id="prvview"
                                                                                  name="perm[prv][view]"
                                                                                  value="1"><label for="prvview">@view_label@</label>
            </div>
            <div class="checkbox clip-check check-warning checkbox-inline"><input type="checkbox" id="prvedit"
                                                                                  name="perm[prv][edit]"
                                                                                  value="1"><label for="prvedit">@edit_btn@</label>
            </div>
            <hr>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <div class="form-group">
            <label class="control-label">
                <i class="fa fa-list"></i> @terms_label@
            </label>
            <div class="checkbox clip-check check-inverse checkbox-inline"><input type="checkbox" id="termsview"
                                                                                  name="perm[terms][view]"
                                                                                  value="1"><label for="termsview">@view_label@</label>
            </div>
            <div class="checkbox clip-check check-warning checkbox-inline"><input type="checkbox" id="termsedit"
                                                                                  name="perm[terms][edit]"
                                                                                  value="1"><label for="termsedit">@edit_btn@</label>
            </div>
            <hr>
        </div>
    </div>
</div>
<legend class="control-label">
    <i class="fa fa-mobile"></i> @mob_app_nav_label@
</legend>
<div class="row">
    <div class="col-sm-12">
        <div class="form-group">
            <label class="control-label">
                <i class="fa fa-mobile"></i> @fcm_notifications_label@
            </label>
            <div class="checkbox clip-check check-inverse checkbox-inline"><input type="checkbox" id="notfview"
                                                                                  name="perm[notf][view]"
                                                                                  value="1"><label for="notfview">@view_label@</label>
            </div>
            <div class="checkbox clip-check check-success checkbox-inline"><input type="checkbox" id="notfsend"
                                                                                  name="perm[notf][add]"
                                                                                  value="1"><label for="notfsend">@send_msgs_label@</label>
            </div>
            <hr>
        </div>
    </div>
</div>