<!-- Modal -->
<div class="modal fade slide-up" id="sendsnotfm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
     aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog modal-dialog modal-sm">
        <div class="modal-content bg-white">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">@send_label@@single_notf@ <span id="notfuname"></span></h4>
            </div>
            <div class="modal-body">
                <form enctype="multipart/form-data" method="post" action="javascript:void(0)" class="add-form"
                      id="sendsnotf">
                    <input type="hidden" name="userid" id="nuserid">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label>
                                    @notf_pros@
                                </label> <span class="symbol required"></span>
                                <select id="notftype" name="notf[type]" class="form-control" required>
                                    <option value="1">@normal_notf@</option>
                                    <option value="2">@msg_notf@</option>
                                    <option value="3">@url_notf@</option>
                                    <option value="7">@view_item_label@</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row hidden" id="notfaction">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label class="control-label">
                                    @notf_action@ <span class="symbol required"></span>
                                </label>
                                <input type="text" placeholder="@input_ph@@notf_action@" class="form-control"
                                       name="notf[action]" required>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label class="control-label">
                                    @notf_title@ <span class="symbol required"></span>
                                </label>
                                <input type="text" placeholder="@input_ph@@notf_title@" class="form-control"
                                       name="notf[title]" required>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label class="control-label">
                                    @notf_message@ <span class="symbol required"></span>
                                </label>
                                <textarea class="form-control" id="editor2" name="notf[msg]" cols="3" rows="3"
                                          required></textarea>
                            </div>
                        </div>
                    </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-warning btn-o" data-dismiss="modal">
                    @cancel_btn@
                </button>
                <button id="send-snotf-btn" type="button" class="btn btn-success">
                    @send_btn@
                </button>
            </div>
            </form>
        </div>
    </div>
</div>