<div class="modal-body">
    <div class="row">
        <div class="col-sm-4">
            <img width="100%" src="iC{{USER_INFO_IMG}}" class="img-rounded">
            <hr>
            <div class="text-center">@city_label@ : iC{{USER_INFO_CITY}}</div>
            iC{{USER_INFO_LOCATION}}
            @username_label@ : iC{{USER_INFO_USERNAME}}<br>
            @state_label@ : iC{{USER_INFO_STATE}} iC{{USER_INFO_NOTF}}<br>
            iC{{USER_INFO_FILES}}
        </div>
        <div class="col-sm-8">
            @name_label@ : iC{{USER_INFO_NAME}}
            <hr>
            @email_label@ : <span dir="ltr">iC{{USER_INFO_EMAIL}}</span>
            <hr>
            iC{{USER_INFO_PHONE}}
            iC{{USER_INFO_MORE}}
            @reg_date@ : iC{{USER_INFO_REG}}
            <hr>
            iC{{USER_INFO_LAST_SEEN}}
            @reg_from@ : iC{{USER_INFO_AUTH}}
            <hr>
        </div>
    </div>
</div>