<!DOCTYPE html>
<html lang="@meta_lang@">
<head>

    <!-- start: META -->
    <meta name="description" content="iC{{META_DESC}}"/>
    <meta name="keywords" content="iC{{META_KEYS}}"/>
    <meta name="robots" content="index,follow"/>
    iC{{HEADER_FAVICON}}
    iC{{HEADER_TAGS}}

    <!-- end: META -->

    <!-- start: GOOGLE FONTS -->
    <link href="https://fonts.googleapis.com/css?family=Lato:300,300i,400,400i,700,700i|Open+Sans:400,400i,700,700i"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Cairo:400,400i,600,600i,700,700i&subset=arabic"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/earlyaccess/droidarabickufi.css" rel="stylesheet">
    <!-- end: GOOGLE FONTS -->


    <!-- =-=-=-=-=-=-= For This Page Only =-=-=-=-=-=-= -->
    iC{{HEADER_STYLE_P}}

    <!-- Title
    ============================================= -->
    iC{{HEADER_TITLE_START}}iC{{SITE_TITLE}}iC{{HEADER_TITLE_END}}
</head>

<body>

<!-- Document Full Container
============================================= -->
<div id="full-container">
    iC{{HEADER}}
    <!-- Content
    ============================================= -->
    <section id="content">
        <div id="content-wrap">
            iC{{PAGE_CONTENT}}
        </div><!-- #content-wrap -->
    </section><!-- #content end -->
    iC{{FOOTER}}
</div>
<!-- #full-container end -->

<a class="scroll-top" href="#"><i class="fa fa-angle-up"></i></a>
<!-- BEGIN JS -->
<!-- BEGIN VENDOR JS -->
iC{{FOOTER_SCRIPTS_VN}}
<!-- END VENDOR JS -->
<!-- BEGIN CORE TEMPLATE JS -->
iC{{FOOTER_SCRIPTS_CORE}}
<!-- END CORE TEMPLATE JS -->
<!-- BEGIN PAGE LEVEL JS -->
iC{{FOOTER_SCRIPTS_P}}
<!-- END PAGE LEVEL JS -->
iC{{FOOTER_SCRIPTS_BC}}
<!-- END JS -->
iC{{FOOTER_TAGS}}
</body>
</html>