<!-- External JavaScripts
 ============================================= -->
<script src="iC{{CONFIG_THEME_URL}}/frontend/assets/js/jquery.js"></script>
<script src="iC{{CONFIG_THEME_URL}}/frontend/assets/js/jRespond.min.js"></script>
<script src="iC{{CONFIG_THEME_URL}}/frontend/assets/js/jquery.easing.min.js"></script>
<script src="iC{{CONFIG_THEME_URL}}/frontend/assets/js/jquery.fitvids.js"></script>
<script src="iC{{CONFIG_THEME_URL}}/frontend/assets/js/jquery.stellar.js"></script>
<script src="iC{{CONFIG_THEME_URL}}/frontend/assets/js/owl.carousel.min.js"></script>
<script src="iC{{CONFIG_THEME_URL}}/frontend/assets/js/hoverIntent.js"></script>
<script src="iC{{CONFIG_THEME_URL}}/frontend/assets/js/simple-scrollbar.min.js"></script>
<script src="iC{{CONFIG_THEME_URL}}/frontend/assets/js/superfish.js"></script>
<script src="iC{{CONFIG_THEME_URL}}/frontend/assets/js/scrollIt.min.js"></script>
<script src="iC{{CONFIG_THEME_URL}}/frontend/assets/js/isotope.pkgd.min.js"></script>
<script src='iC{{CONFIG_THEME_URL}}/frontend/assets/js/jquery.magnific-popup.min.js'></script>
<script src="iC{{CONFIG_THEME_URL}}/frontend/assets/js/jquery.waitforimages.min.js"></script>
<script src='iC{{CONFIG_THEME_URL}}/frontend/assets/js/jquery.validate.min.js'></script>
<script src='iC{{CONFIG_THEME_URL}}/frontend/assets/js/functions.js'></script>