<!-- start: DYNAMIC TABLE -->
<div class="container-fluid container-fullw bg-white">
    <h5 class="over-title margin-bottom-15"><span class="text-bold">@delivery_tracking_label@</span>
        <div class="checkbox clip-check check-success checkbox-inline"><input type="checkbox" id="autozoom" value="1"
                                                                              checked=""><label for="autozoom">@auto_zoom_label@</label>
        </div>
    </h5>
    <!-- start: MAP -->
    <div class="map" id="map"></div>
    <!-- end: MAP -->
</div>