<!-- === Our Services =========== -->
<div id="download-app" class="flat-section download-app" data-scroll-index="1">
    <div class="section-title">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <h2>@3lfraza_app@</h2>
                </div><!-- .col-md-8 end -->
            </div><!-- .row end -->
        </div><!-- .container end -->

    </div><!-- .section-title end -->

    <div class="section-content">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                    <img src="iC{{CONFIG_THEME_URL}}/frontend/assets/images/app-showcase-@lang_dir@.png" width="50%"
                         alt="">
                    <a href="https://play.google.com/store/apps/details?id=com.alfraza.app" target="_blank"><img
                                src="iC{{CONFIG_THEME_URL}}/frontend/assets/images/play-store.png" width="30%"
                                alt=""></a>
                </div>

            </div><!-- .col-md-12 end -->
        </div><!-- .row end -->
    </div><!-- .container end -->

</div><!-- .section-content end -->

<!-- === Get Connected =========== -->
<div id="get-connected" class="flat-section get-connected" data-scroll-index="2">
    <div class="section-title">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <h2>@menu_contact@</h2>
                </div><!-- .col-md-8 end -->
            </div><!-- .row end -->
        </div><!-- .container end -->

    </div><!-- .section-title end -->

    <div class="section-content">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="connect-box">
                        <p></p>
                        <div class="col-sm-4">
                            <ul class="social-icons">
                                <li><a class="si-facebook" href="https://www.facebook.com/3lfraza" target="_blank"><i class="fa fa-facebook"></i></a></li>
                            </ul><!-- .social-icons end -->
                        </div>
                        <div class="col-sm-4">
                            <ul class="contact-info">
                                <li><a href="tel:+201018823777"><i class="fa fa-phone"></i><span dir="ltr">(+2) 01018823777</span></a> <a href="tel:+201018823111"><i class="fa fa-phone"></i><span dir="ltr">(+2) 01018823111</span></a></li>
                            </ul>
                        </div>
                        <div class="col-sm-4">
                            <ul class="contact-info">
                                <li><i class="fa fa-envelope"></i>info@3lfraza.com</li>
                            </ul>
                        </div>
                    </div><!-- .connect-box end -->
                </div><!-- .row end -->
            </div><!-- .container end -->
        </div><!-- .section-content end -->
    </div><!-- .flat-section end -->