<!-- start: DYNAMIC TABLE -->
<div class="container-fluid container-fullw bg-white">
    <div class="row">
        <div class="col-md-12">
            <h5 class="over-title margin-bottom-15"><span class="text-bold">@view_label@ @location_alert_label@</span>
            </h5>
            <div class="row">
                <div class="col-sm-4">
                    <div class="input-group"><span class="input-group-addon"><i class="fa fa-search"></i></span><input
                                type="text" placeholder="@search_input_ph@" id="search-table" value="iC{{SEARCH_Q}}"
                                class="form-control"></div>
                </div>
                <div class="col-sm-5">

                </div>
                <div class="col-sm-3  pull-left">
                </div>
            </div>
            <div class="table-responsive">
                <table class="table-striped" id="dtTbl">
                    <thead>
                    <tr>
                        <th>@count_label@</th>
                        <th>@type_label@</th>
                        <th>@name_label@</th>
                        <th>@phone_label@</th>
                        <th>@email_label@</th>
                        <th>@address_label@</th>
                        <th>@added_time_label@</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
