<!-- Footer Mini
		============================================= -->
<footer id="footer-mini">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <a class="logo-footer" href="iC{{CONFIG_SITE_URL}}"><img
                            src="iC{{CONFIG_THEME_URL}}/frontend/assets/images/files/logo-footer-rtl.png"
                            alt="@system_name@"></a>
                <div class="copyrights-message">@copyright_1@ © iC{{YEAR}} <span>@system_name@</span>. @copyright_2@
                    <br>
                    <a href="iC{{RESET_PASS_URL}}"><i class="fa fa-key"></i> @reset_password_label@</a> | <a href="iC{{PRIVACY_URL}}"><i class="fa fa-lock"></i> @privacy_label@</a> | <a href="iC{{TERMS_URL}}"><i class="fa fa-book"></i> @terms_label@</a>
                </div>
            </div><!-- .col-md-12 end -->
        </div><!-- .row end -->
    </div><!-- .container end -->

</footer>
<!-- #footer-mini end -->