<!-- Header
		============================================= -->
<header id="header">
    <div id="header-wrap">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <a class="logo" href="iC{{CONFIG_SITE_URL}}">
                        <img src="iC{{CONFIG_THEME_URL}}/frontend/assets/images/files/logo-rtl.png" alt="@system_name@">
                        <h5><span class="colored">@system_name@</span></h5>
                    </a><!-- .logo end -->
                    <ul id="main-menu" class="main-menu">
                        <li><a data-scroll-nav="1" href="#download-app"><i class="fa fa-mobile"></i> @3lfraza_app@</a></li>
                        <li><a data-scroll-nav="2" href="#get-connected"><i class="fa fa-phone"></i> @menu_contact@</a></li>
                    </ul>
                    <ul class="main-menu">
                        <li><a href="iC{{LANG_URL}}"><i class="fa fa-globe"></i> iC{{LANG_NAME}}</a></li>
                    </ul>
                    <div class="mobile-menu-btn hamburger hamburger--slider">
								<span class="hamburger-box">
									<span class="hamburger-inner"></span>
								</span>
                    </div><!-- .mobile-menu-btn -->
                    <div id="mobile-menu" class="text-center">
                        <a class="btn btn-primary" href="iC{{LANG_URL}}"><i class="fa fa-globe"></i> iC{{LANG_NAME}}</a>
                    </div><!-- #mobile-menu end -->
                </div><!-- .col-md-12 end -->
            </div><!-- .row end -->
        </div><!-- .container end -->
    </div><!-- #header-wrap end -->
</header><!-- #header end -->