<!-- Modal -->
<div class="modal fade slide-up" id="addnew" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
     aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog modal-dialog modal-sm">
        <div class="modal-content bg-white">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">@add_new_btn@</h4>
            </div>
            <div class="modal-body">
                <h5 class="over-title margin-bottom-15"><span class="text-bold">@seller_cats_label@</span></h5>
                <form enctype="multipart/form-data" method="post" action="javascript:void(0)" class="add-form"
                      id="addcat">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label class="control-label">
                                    @cat_order_label@
                                </label>
                                <input type="number" placeholder="@cat_order_ph@" class="form-control" id="catorder"
                                       name="order">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        iC{{MORE_ADD_MODAL}}
                    </div>
                    <div id="mainsel" class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label for="catadd">
                                    @select_main_cat@
                                </label> <span class="symbol required"></span>
                                <select id="catadd" name="cat" class="form-control" required>

                                </select>
                            </div>
                        </div>
                    </div>
                    <div id="subsel" class="row hidden">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label for="subcatadd">
                                    @select_sub_cat@
                                </label> <span class="symbol required"></span>
                                <select id="subcatadd" name="subcat" class="form-control" required>

                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label class="control-label">
                                    @title_in_lang@@ar_lang@ <span class="symbol required"></span>
                                </label>
                                <input type="text" placeholder="@input_ph@@title_in_lang@@ar_lang@" class="form-control"
                                       id="titlear" name="title[ar]" required>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label class="control-label">
                                    @title_in_lang@@en_lang@
                                </label>
                                <input type="text" placeholder="@input_ph@@title_in_lang@@en_lang@" class="form-control"
                                       id="titleen" name="title[en]">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label class="control-label">
                                    @main_photo_label@
                                </label>
                                <input name="fimage" type="file" class="form-control">

                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-warning btn-o" data-dismiss="modal">
                    @cancel_btn@
                </button>
                <button id="add-btn" type="button" class="btn btn-success">
                    @add_new_btn@
                </button>
            </div>
        </div>
    </div>
</div>