<div class="modal-body">
    <div class="row">
        <div class="col-sm-12">
            iC{{CAT_MAIN_IMG}}
            @category_label@ : iC{{CATNAME}}
            <hr>
        </div>
        <div class="col-sm-12">
            @title_in_lang@@ar_lang@ : iC{{CAT_TITLE_AR}}
            <hr>
            @title_in_lang@@en_lang@ : iC{{CAT_TITLE_EN}}
            <hr>
        </div>
    </div>

</div>