<link rel="stylesheet" href="iC{{CONFIG_THEME_URL}}/backend/vendor/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="iC{{CONFIG_THEME_URL}}/backend/vendor/fontawesome/css/font-awesome.min.css">
<link rel="stylesheet" href="iC{{CONFIG_THEME_URL}}/backend/vendor/themify-icons/themify-icons.min.css">
<link href="iC{{CONFIG_THEME_URL}}/backend/vendor/animate.css/animate.min.css" rel="stylesheet" media="screen">
<link href="iC{{CONFIG_THEME_URL}}/backend/vendor/perfect-scrollbar/perfect-scrollbar.min.css" rel="stylesheet"
      media="screen">
<link href="iC{{CONFIG_THEME_URL}}/backend/vendor/switchery/switchery.min.css" rel="stylesheet" media="screen">