<!-- START CONTAINER FLUID -->
<div class="container-fluid container-fixed-lg">
    <!-- START PANEL -->
    <div class="panel panel-transparent">
        <div class="panel-heading">
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-sm-4">
                    <div class="panel panel-default" data-pages="portlet">
                        <div class="panel-heading">
                            <div class="panel-title"><span class="fa-stack fa-lg"><i
                                            class="fa fa-square-o fa-stack-2x"></i><i
                                            class="fa  fa-users fa-stack-1x"></i></span></div>

                        </div>
                        <div class="panel-body">
                            iC{{MSG_RECIP}}
                        </div>
                    </div>
                </div>
                <div class="col-sm-8">
                    <div class="panel panel-default" data-pages="portlet">
                        <div class="panel-heading">
                            <div class="panel-title"><span class="fa-stack fa-lg"><i
                                            class="fa fa-square-o fa-stack-2x"></i><i
                                            class="fa fa-comments-o fa-stack-1x"></i></span> <span id="msg_head">iC{{RECP_NAME}}</span>
                            </div>

                        </div>
                        <div id="msg_body" class="panel-body">
                            iC{{RECP_MSG}}
                            <div class="clearfix"><br></div>
                            iC{{RECP_MSG_REPLAY}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- END PANEL -->
    </div>
    <!-- END CONTAINER FLUID -->
</div>
