<div id="message_iC{{LIST_MESSAGE_ID}}" class="col-sm-12">
    <div class="row">
        <div class="col-sm-1">
            <img class="avatar" width="100%" src="iC{{LIST_MESSAGE_IMG}}" alt="iC{{LIST_MESSAGE_NAME}}">
        </div>


        <div class="col-sm-11">
            <a>
                iC{{LIST_MESSAGE_NAME}}
            </a>

            <span class="message-text">
                    iC{{LIST_MESSAGE_TEXT}}
                </span>
            <span class="pull-left label label-default" title="iC{{LIST_MESSAGE_TIME}}">
                    iC{{LIST_MESSAGE_TIME}}
                </span>
        </div>
    </div>
</div>