<a href="#" onclick="VMsgUser(iC{{LIST_RECIPIENT_ID}});">
    <div id="msg_iC{{LIST_RECIPIENT_ID}}" class="col-sm-12">
        <div class="col-sm-3">
            <img width="100%" alt="iC{{LIST_RECIPIENT_NAME}}" src="iC{{LIST_RECIPIENT_THUMBNAIL_URL}}" class="col-top">
        </div>
        <div class="col-sm-9">
					  <span class="block text-master hint-text fs-12">
					  iC{{LIST_RECIPIENT_NAME}}
					  </span>
        </div>
    </div>
</a>