<div class="row">
    <div class="col-sm-12">
        <div class="form-group form-group-default input-group col-sm-12">
            <label>@send_msg_label@ <span id="toname">iC{{RECP_NAME}}</span></label>
            <input type="text" id="msgtext" class="form-control" placeholder="@msg_text_label@">
            <span class="input-group-addon primary">
					  <button type="button" onclick="sendRMsg(iC{{USER_ID}},iC{{RECP_ID}});"
                              class="btn btn-primary btn-block m-t-5">
					  @send_btn@</button></span>
        </div>
    </div>
</div>