<!-- Modal -->
<div class="modal fade slide-up" id="addnew" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
     aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog modal-dialog modal-sm">
        <div class="modal-content bg-white">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">@add_new_btn@</h4>
            </div>
            <div class="modal-body">
                <h5 class="over-title margin-bottom-15"><span class="text-bold">@cities_label@</span></h5>
                <form enctype="multipart/form-data" method="post" action="javascript:void(0)" class="add-form"
                      id="additm">
                    <div class="row">
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label for="groupadd">
                                    @select_group_label@
                                </label> <span class="symbol required"></span>
                                <select id="groupadd" name="city_group" class="form-control" required>
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label class="control-label">
                                    @title_in_lang@@ar_lang@ <span class="symbol required"></span>
                                </label>
                                <input type="text" placeholder="@input_ph@@title_in_lang@@ar_lang@" class="form-control"
                                       id="titlear" name="title[ar]" required>
                            </div>
                            <div class="form-group">
                                <label class="control-label">
                                    @title_in_lang@@en_lang@ <span class="symbol required"></span>
                                </label>
                                <input type="text" placeholder="@input_ph@@title_in_lang@@en_lang@" class="form-control"
                                       id="titleen" name="title[en]" required>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label class="control-label">
                                    @lat_label@ <span class="symbol required"></span>
                                </label>
                                <input type="number" placeholder="@input_ph@@lat_label@" class="form-control"
                                       name="lat" required>
                            </div>
                            <div class="form-group">
                                <label class="control-label">
                                    @lon_label@ <span class="symbol required"></span>
                                </label>
                                <input type="number" placeholder="@input_ph@@lon_label@" class="form-control"
                                       name="lon" required>
                            </div>
                            <div class="form-group">
                                <label class="control-label">
                                    @radius_label@ <span class="symbol required"></span>
                                </label>
                                <input type="number" placeholder="@input_ph@@radius_label@" class="form-control"
                                       name="radius" required>
                            </div>
                            <div class="form-group">
                                <label class="control-label">
                                    @shipping_cost_label@ <span class="symbol required"></span>
                                </label>
                                <input type="number" placeholder="@input_ph@@shipping_cost_label@" class="form-control"
                                       name="shipping" required>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-warning btn-o" data-dismiss="modal">
                    @cancel_btn@
                </button>
                <button id="add-btn" type="button" class="btn btn-success">
                    @add_new_btn@
                </button>
            </div>
        </div>
    </div>
</div>