<!-- start: DYNAMIC TABLE -->
<div class="container-fluid container-fullw">
    <div class="row">
        <div class="col-sm-12">
            <!-- start: MAP -->
            <div class="map" id="map"></div>
            <!-- end: MAP -->
        </div>
    </div>
</div>
<div class="container-fluid container-fullw bg-white">
    <div class="row">
        <div class="col-md-12">
            <h5 class="over-title margin-bottom-15"><span class="text-bold">@manage_label@@cities_label@</span>
            </h5>
            <div class="row">
                <div class="col-sm-3">
                    <div class="input-group"><span class="input-group-addon"><i class="fa fa-search"></i></span><input
                            type="text" placeholder="@search_input_ph@" id="search-table" class="form-control">
                    </div>
                </div>
                <div class="col-sm-7">
                </div>
                <div class="col-sm-2  pull-left">
                    iC{{ADD_NEW_BTN}}
                </div>
            </div>
            <div class="table-responsive">
                <table class="table-striped" id="itmstbl">
                    <thead>
                    <tr>
                        <th>@count_label@</th>
                        <th>@city_name@</th>
                        <th>@group_label@</th>
                        <th>@lat_label@</th>
                        <th>@lon_label@</th>
                        <th>@radius_label@</th>
                        <th>@shipping_cost_label@</th>
                        <th>@added_time_label@</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
