<!-- Activate Modal -->
<div class="modal fade modal-aside horizontal left" tabindex="-1" id="activateitem" role="dialog"
     aria-labelledby="myLargeModalLabel" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog modal-dialog modal-sm">
        <div class="modal-content bg-white">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">@confirm_dialouge@</h4>
            </div>
            <div class="modal-body">
                <form method="post" action="javascript:void(0)" id="activate-form">
                    <input type="hidden" name="itemid" id="activeid">
                    @are_you_sure@ <span class="text-bold " id="actaction"></span> @question_mark@
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary btn-o" data-dismiss="modal">
                    @cancel_btn@
                </button>
                <button type="button" id="activate-btn" class="btn ">

                </button>
            </div>
        </div>
    </div>
</div>
<!-- /Activate Modal -->
