<!-- Refund Modal -->
<div class="modal fade modal-aside horizontal left" tabindex="-1" id="refunditem" role="dialog"
     aria-labelledby="myLargeModalLabel" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog modal-dialog modal-sm">
        <div class="modal-content bg-white">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">@confirm_dialouge@</h4>
            </div>
            <div class="modal-body">
                <form method="post" action="javascript:void(0)" id="refund-form">
                    <input type="hidden" name="itemid" id="refid">
                    @are_you_sure@ @refund_label@ <span class="text-danger text-bold" id="refname"></span>
                    @question_mark@
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary btn-o" data-dismiss="modal">
                    @cancel_btn@
                </button>
                <button type="button" id="ref-btn" class="btn btn-danger">
                    @refund_label@
                </button>
            </div>
        </div>
    </div>
</div>
<!-- /Refund Modal -->