<!-- start: USER PROFILE -->
<div class="container-fluid container-fullw bg-white">
    <div class="row">
        <div class="col-md-12">
            <div class="tabbable">
                <ul class="nav nav-tabs tab-padding tab-space-3 tab-blue" id="myTab4">
                    <li class="active">
                        <a data-toggle="tab" href="#panel_edit_account">
                            @edit_btn@
                        </a>
                    </li>
                </ul>
                <div class="tab-content">
                    <div id="panel_edit_account" class="tab-pane fade in active">
                        <div class="row">
                            <div class="col-sm-5 col-md-5">
                                <div class="user-left">
                                    <div class="center">
                                        <h4>iC{{USER_NAME}}</h4>
                                        <div class="fileinput fileinput-new" data-provides="fileinput">
                                            <div class="user-image">
                                                <div class="fileinput-new thumbnail useravatar"><img
                                                            src="iC{{USER_AVATAR_URL}}" alt="iC{{USER_NAME}}">
                                                </div>
                                            </div>
                                        </div>
                                        <hr>
                                    </div>
                                    <table class="table table-condensed">
                                        <thead>
                                        <tr>
                                            <th colspan="3">@contact_info_add@</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <tr>
                                            <td>@email_label@:</td>
                                            <td>
                                                <a href="">
                                                    iC{{USER_EMAIL}}
                                                </a></td>
                                        </tr>
                                        <tr>
                                            <td>@phone_label@:</td>
                                            <td><span dir="ltr">iC{{USER_PHONE}}</span></td>
                                        </tr>
                                        </tbody>
                                    </table>
                                    <table class="table">
                                        <thead>
                                        <tr>
                                            <th colspan="3">@user_info@</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <tr>
                                            <td>@last_seen_web@</td>
                                            <td>iC{{USER_LAST_USE}}</td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="col-sm-7 col-md-7">
                                <form role="form" id="form-myprofile" action="javascript:void(0)"
                                      enctype="multipart/form-data">
                                    <fieldset>
                                        <legend>
                                            @edit_btn@ @user_info@
                                        </legend>
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label class="control-label">
                                                        @email_label@
                                                    </label>
                                                    <input type="email" placeholder="@email_ph@" class="form-control"
                                                           id="email" value="iC{{USER_EMAIL}}" name="email">
                                                </div>
                                                <div class="form-group">
                                                    <label class="control-label">
                                                        @phone_label@
                                                    </label>
                                                    <input type="text" placeholder="@enter_phone_ph@"
                                                           class="form-control" id="phone" value="iC{{USER_PHONE}}"
                                                           name="phone">
                                                </div>
                                                <div class="form-group">
                                                    <label class="control-label">
                                                        @old_password_label@
                                                    </label>
                                                    <input type="password" class="form-control" name="current_password"
                                                           id="current_password">
                                                </div>
                                                <div class="form-group">
                                                    <label class="control-label">
                                                        @new_password_label@
                                                    </label>
                                                    <input type="password" class="form-control" id="new_password"
                                                           name="new_password">
                                                </div>

                                                <div class="form-group">
                                                    <label>
                                                        @personal_image_label@
                                                    </label>
                                                    <div class="fileinput fileinput-new" data-provides="fileinput">
                                                        <div class="user-edit-image-buttons">
																			<span class="btn btn-azure btn-file"><span
                                                                                        class="fileinput-new"><i
                                                                                            class="fa fa-picture"></i> @upload_pic_btn@</span>
																				<input type="file" id="user_image"
                                                                                       name="user_image">
																			</span>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </fieldset>
                                    <div class="row">
                                        <div class="col-md-7">
                                        </div>
                                        <div class="col-md-5">
                                            <div class="btn btn-primary hidden" id="error"></div>
                                            <button id="submit-btn" type="submit" class="btn btn-primary pull-right"><i
                                                        id="loading-spin"
                                                        class="fa fa-spinner fa-spin fa-fw hidden"></i>
                                                @save_changes_btn@ <i class="fa fa-arrow-circle-right"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end: USER PROFILE -->