<!-- Start favicon -->
    <link rel="apple-touch-icon" sizes="57x57" href="iC{{CONFIG_SITE_URL}}/icons/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="iC{{CONFIG_SITE_URL}}/icons/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="iC{{CONFIG_SITE_URL}}/icons/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="iC{{CONFIG_SITE_URL}}/icons/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="iC{{CONFIG_SITE_URL}}/icons/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="iC{{CONFIG_SITE_URL}}/icons/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="iC{{CONFIG_SITE_URL}}/icons/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="iC{{CONFIG_SITE_URL}}/icons/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="iC{{CONFIG_SITE_URL}}/icons/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="iC{{CONFIG_SITE_URL}}/icons/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="iC{{CONFIG_SITE_URL}}/icons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="iC{{CONFIG_SITE_URL}}/icons/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="iC{{CONFIG_SITE_URL}}/icons/favicon-16x16.png">
    <link rel="manifest" href="iC{{CONFIG_SITE_URL}}/icons/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="iC{{CONFIG_SITE_URL}}/icons/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
    <link rel="icon" type="image/x-icon" href="iC{{CONFIG_SITE_URL}}/favicon.ico"/>
    <!-- End favicon -->
