<!DOCTYPE html>
<!--[if IE 8]>
<html class="ie8" lang="@lang_code@"><![endif]-->
<!--[if IE 9]>
<html class="ie9" lang="@lang_code@"><![endif]-->
<!--[if !IE]><!-->
<html lang="@lang_code@">
<!--<![endif]-->
<!-- start: HEAD -->
<head>
    iC{{HEADER_TITLE_START}}iC{{SITE_TITLE}}iC{{HEADER_TITLE_END}}
    <!-- start: META -->
    iC{{HEADER_META}}
    iC{{HEADER_FAVICON}}
    <!-- end: META -->
    <!-- start: GOOGLE FONTS -->
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,400italic,600,700|Raleway:300,400,500,600,700|Crete+Round:400italic"
          rel="stylesheet" type="text/css"/>
    <!-- end: GOOGLE FONTS -->
    <!-- start: MAIN CSS -->
    iC{{HEADER_STYLESHEET_MAIN}}
    <!-- end: MAIN CSS -->
    <!-- start: Theme CSS -->
    iC{{HEADER_STYLESHEET_THEME}}
    <!-- start: Theme CSS -->
    <!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
    iC{{HEADER_STYLESHEET_PAGE}}
    <!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
    iC{{HEADER_TAGS}}
</head>
<!-- end: HEAD -->
<body class="iC{{BODY_CLASS}}">
<div id="app">
    <!-- sidebar -->
    iC{{SIDEBAR}}
    <!-- / sidebar -->
    <div class="app-content">
        <!-- start: TOP NAVBAR -->
        iC{{HEADER}}
        <!-- end: TOP NAVBAR -->
        <div class="main-content">
            <div class="wrap-content container" id="container">
                <!-- start: PAGE TITLE -->
                iC{{PAGE_HEADER}}
                <!-- end: PAGE TITLE -->
                <!-- START PAGE CONTENT -->
                iC{{PAGE_CONTENT}}
                <!-- END PAGE CONTENT -->
                <!-- START PAGE MODALS -->
                iC{{PAGE_MODALS}}
                <!-- END PAGE MODALS -->
            </div>
        </div>
    </div>
    <!-- start: FOOTER -->
    iC{{FOOTER}}
    <!-- end: FOOTER -->
    <!-- start: SETTINGS -->
    <div class="settings panel panel-default hidden-xs hidden-sm" id="settings">
        <button ct-toggle="toggle" data-toggle-class="active" data-toggle-target="#settings" class="btn btn-default">
            <i class="fa fa-spin fa-gear"></i>
        </button>
        <div class="panel-heading">
            Style Selector
        </div>
        <div class="panel-body">
            <!-- start: FIXED HEADER -->
            <div class="setting-box clearfix">
                <span class="setting-title pull-left"> Fixed header</span>
                <span class="setting-switch pull-right">
							<input type="checkbox" class="js-switch" id="fixed-header"/>
						</span>
            </div>
            <!-- end: FIXED HEADER -->
            <!-- start: FIXED SIDEBAR -->
            <div class="setting-box clearfix">
                <span class="setting-title pull-left">Fixed sidebar</span>
                <span class="setting-switch pull-right">
							<input type="checkbox" class="js-switch" id="fixed-sidebar"/>
						</span>
            </div>
            <!-- end: FIXED SIDEBAR -->
            <!-- start: CLOSED SIDEBAR -->
            <div class="setting-box clearfix">
                <span class="setting-title pull-left">Closed sidebar</span>
                <span class="setting-switch pull-right">
							<input type="checkbox" class="js-switch" id="closed-sidebar"/>
						</span>
            </div>
            <!-- end: CLOSED SIDEBAR -->
            <!-- start: FIXED FOOTER -->
            <div class="setting-box clearfix">
                <span class="setting-title pull-left">Fixed footer</span>
                <span class="setting-switch pull-right">
							<input type="checkbox" class="js-switch" id="fixed-footer"/>
						</span>
            </div>
            <!-- end: FIXED FOOTER -->
            <!-- start: THEME SWITCHER -->
            <div class="colors-row setting-box">
                <div class="color-theme theme-1">
                    <div class="color-layout">
                        <label>
                            <input type="radio" name="setting-theme" value="theme-1">
                            <span class="ti-check"></span>
                            <span class="split header"> <span class="color th-header"></span> <span
                                        class="color th-collapse"></span> </span>
                            <span class="split"> <span class="color th-sidebar"><i class="element"></i></span> <span
                                        class="color th-body"></span> </span>
                        </label>
                    </div>
                </div>
                <div class="color-theme theme-2">
                    <div class="color-layout">
                        <label>
                            <input type="radio" name="setting-theme" value="theme-2">
                            <span class="ti-check"></span>
                            <span class="split header"> <span class="color th-header"></span> <span
                                        class="color th-collapse"></span> </span>
                            <span class="split"> <span class="color th-sidebar"><i class="element"></i></span> <span
                                        class="color th-body"></span> </span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="colors-row setting-box">
                <div class="color-theme theme-3">
                    <div class="color-layout">
                        <label>
                            <input type="radio" name="setting-theme" value="theme-3">
                            <span class="ti-check"></span>
                            <span class="split header"> <span class="color th-header"></span> <span
                                        class="color th-collapse"></span> </span>
                            <span class="split"> <span class="color th-sidebar"><i class="element"></i></span> <span
                                        class="color th-body"></span> </span>
                        </label>
                    </div>
                </div>
                <div class="color-theme theme-4">
                    <div class="color-layout">
                        <label>
                            <input type="radio" name="setting-theme" value="theme-4">
                            <span class="ti-check"></span>
                            <span class="split header"> <span class="color th-header"></span> <span
                                        class="color th-collapse"></span> </span>
                            <span class="split"> <span class="color th-sidebar"><i class="element"></i></span> <span
                                        class="color th-body"></span> </span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="colors-row setting-box">
                <div class="color-theme theme-5">
                    <div class="color-layout">
                        <label>
                            <input type="radio" name="setting-theme" value="theme-5">
                            <span class="ti-check"></span>
                            <span class="split header"> <span class="color th-header"></span> <span
                                        class="color th-collapse"></span> </span>
                            <span class="split"> <span class="color th-sidebar"><i class="element"></i></span> <span
                                        class="color th-body"></span> </span>
                        </label>
                    </div>
                </div>
                <div class="color-theme theme-6">
                    <div class="color-layout">
                        <label>
                            <input type="radio" name="setting-theme" value="theme-6">
                            <span class="ti-check"></span>
                            <span class="split header"> <span class="color th-header"></span> <span
                                        class="color th-collapse"></span> </span>
                            <span class="split"> <span class="color th-sidebar"><i class="element"></i></span> <span
                                        class="color th-body"></span> </span>
                        </label>
                    </div>
                </div>
            </div>
            <!-- end: THEME SWITCHER -->
        </div>
    </div>
    <!-- end: SETTINGS -->
</div>
<!-- BEGIN JS -->
<!-- BEGIN VENDOR JS -->
iC{{FOOTER_SCRIPTS_VN}}
<!-- END VENDOR JS -->
<!-- BEGIN CORE THEME JS -->
iC{{FOOTER_SCRIPTS_CORE}}
<!-- END CORE THEME JS -->
<!-- BEGIN PAGE LEVEL JS -->
iC{{FOOTER_SCRIPTS_P}}
<!-- END PAGE LEVEL JS -->
iC{{FOOTER_JQUERY_P}}
iC{{FOOTER_JQUERY_BC}}
<!-- END JS -->
iC{{FOOTER_TAGS}}
</body>
</html>