<!DOCTYPE html>
<!--[if IE 8]>
<html class="ie8" lang="@lang_code@"><![endif]-->
<!--[if IE 9]>
<html class="ie9" lang="@lang_code@"><![endif]-->
<!--[if !IE]><!-->
<html lang="@lang_code@" dir="@lang_dir@">
<!--<![endif]-->
<!-- start: HEAD -->
<head>
    iC{{HEADER_TITLE_START}}iC{{SITE_TITLE}}iC{{HEADER_TITLE_END}}
    <!-- start: META -->
    <meta name="robots" content="noindex"/>
    iC{{HEADER_META}}
    iC{{HEADER_FAVICON}}
    <!-- end: META -->
    <!-- start: MAIN CSS -->
    iC{{HEADER_STYLESHEET_MAIN}}
    <!-- end: MAIN CSS -->
    <!-- start: Theme CSS -->
    iC{{HEADER_STYLESHEET_THEME}}
    <!-- start: Theme CSS -->
    <!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
    iC{{HEADER_STYLESHEET_PAGE}}
    <!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
    iC{{HEADER_TAGS}}
</head>
<!-- end: HEAD -->

<body class="iC{{BODY_CLASS}}">
<!-- START PAGE CONTENT -->
iC{{PAGE_CONTENT}}
<!-- END PAGE CONTENT -->

<!-- BEGIN JS -->
<!-- BEGIN VENDOR JS -->
iC{{FOOTER_SCRIPTS_VN}}
<!-- END VENDOR JS -->
<!-- BEGIN CORE THEME JS -->
iC{{FOOTER_SCRIPTS_CORE}}
<!-- END CORE THEME JS -->
<!-- BEGIN PAGE LEVEL JS -->
iC{{FOOTER_SCRIPTS_P}}
<!-- END PAGE LEVEL JS -->
iC{{FOOTER_JQUERY_P}}
iC{{FOOTER_JQUERY_BC}}
<!-- END JS -->
iC{{FOOTER_TAGS}}
</body>
</html>